#! /usr/bin/env bash
exec /home/vboxuser/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/vboxuser/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/vboxuser/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/vboxuser/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/vboxuser/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/vboxuser/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x2dc0c70 .scope module, "Mul_Top_TB" "Mul_Top_TB" 2 3;
 .timescale -9 -12;
P_0x2dca4b0 .param/real "DUTY_CYCLE" 0 2 41, Cr<m4000000000000000gfc1>; value=0.500000
P_0x2dca4f0 .param/l "PERIOD" 0 2 40, +C4<00000000000000000000000000010100>;
v0x2ded680_0 .var "Ain", 15 0;
v0x2ded7b0_0 .var "B", 15 0;
v0x2ded8c0_0 .net "C", 31 0, v0x2deb030_0;  1 drivers
v0x2ded960_0 .var "clk", 0 0;
v0x2deda00_0 .net "done", 0 0, v0x2de9c80_0;  1 drivers
v0x2dedb40_0 .var "init", 0 0;
v0x2dedc30_0 .var "rst", 0 0;
E_0x2dc2b10 .event anyedge, v0x2de9c80_0;
S_0x2dc0f30 .scope module, "uut" "Mul_Top" 2 20, 3 1 0, S_0x2dc0c70;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "init";
    .port_info 3 /INPUT 16 "Ain";
    .port_info 4 /INPUT 16 "B";
    .port_info 5 /OUTPUT 32 "C";
    .port_info 6 /OUTPUT 1 "done";
v0x2dec570_0 .net "A", 15 0, v0x2dea8c0_0;  1 drivers
v0x2dec650_0 .net "Ain", 15 0, v0x2ded680_0;  1 drivers
v0x2dec710_0 .net "B", 15 0, v0x2ded7b0_0;  1 drivers
v0x2dec7e0_0 .net "C", 31 0, v0x2deb030_0;  alias, 1 drivers
v0x2dec880_0 .net "CONTROL", 0 0, L_0x2deddc0;  1 drivers
v0x2dec970_0 .net "C_temp", 31 0, L_0x2dfe130;  1 drivers
v0x2deca60_0 .net "D", 15 0, v0x2deb870_0;  1 drivers
v0x2decb70_0 .net "DONE", 0 0, L_0x2dede60;  1 drivers
v0x2decc60_0 .net "DSHT", 0 0, v0x2de9b40_0;  1 drivers
v0x2decd90_0 .net "clk", 0 0, v0x2ded960_0;  1 drivers
v0x2dece30_0 .net "done", 0 0, v0x2de9c80_0;  alias, 1 drivers
v0x2deced0_0 .net "i", 3 0, v0x2dec150_0;  1 drivers
v0x2ded000_0 .net "i_temp", 3 0, L_0x2dedcd0;  1 drivers
v0x2ded0c0_0 .net "init", 0 0, v0x2dedb40_0;  1 drivers
v0x2ded160_0 .net "load_A", 0 0, v0x2de9e30_0;  1 drivers
v0x2ded250_0 .net "load_C", 0 0, v0x2de9ef0_0;  1 drivers
v0x2ded340_0 .net "load_D", 0 0, v0x2de9fb0_0;  1 drivers
v0x2ded430_0 .net "load_i", 0 0, v0x2dea100_0;  1 drivers
v0x2ded520_0 .net "rst", 0 0, v0x2dedc30_0;  1 drivers
S_0x2dbf960 .scope module, "ADD" "ADD_D" 3 118, 4 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "CONTROL";
    .port_info 1 /OUTPUT 32 "C_temp";
    .port_info 2 /INPUT 16 "D";
    .port_info 3 /INPUT 32 "C";
v0x2dac010_0 .net "C", 31 0, v0x2deb030_0;  alias, 1 drivers
v0x2dabea0_0 .net "CONTROL", 0 0, L_0x2deddc0;  alias, 1 drivers
v0x2dcb200_0 .net "C_temp", 31 0, L_0x2dfe130;  alias, 1 drivers
v0x2dcb4a0_0 .net "D", 15 0, v0x2deb870_0;  alias, 1 drivers
L_0x7292239860a8 .functor BUFT 1, C4<0000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2d9c550_0 .net/2u *"_ivl_0", 15 0, L_0x7292239860a8;  1 drivers
v0x2d9b770_0 .net *"_ivl_2", 31 0, L_0x2dfdf10;  1 drivers
v0x2d9be00_0 .net *"_ivl_4", 31 0, L_0x2dfe000;  1 drivers
L_0x2dfdf10 .concat [ 16 16 0 0], v0x2deb870_0, L_0x7292239860a8;
L_0x2dfe000 .arith/sum 32, v0x2deb030_0, L_0x2dfdf10;
L_0x2dfe130 .functor MUXZ 32, v0x2deb030_0, L_0x2dfe000, L_0x2deddc0, C4<>;
S_0x2de8010 .scope module, "CA" "Comp_Ai" 3 101, 5 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 16 "A";
    .port_info 1 /INPUT 4 "i";
    .port_info 2 /OUTPUT 1 "CONTROL";
v0x2de8210_0 .net "A", 15 0, v0x2dea8c0_0;  alias, 1 drivers
v0x2de8310_0 .net "CONTROL", 0 0, L_0x2deddc0;  alias, 1 drivers
v0x2de83d0_0 .net "i", 3 0, v0x2dec150_0;  alias, 1 drivers
L_0x2deddc0 .part/v v0x2dea8c0_0, v0x2dec150_0, 1;
S_0x2de84d0 .scope module, "CHK" "Check_i" 3 110, 6 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 4 "i";
    .port_info 1 /OUTPUT 1 "DONE";
v0x2de8700_0 .net "DONE", 0 0, L_0x2dede60;  alias, 1 drivers
L_0x729223986060 .functor BUFT 1, C4<1111>, C4<0>, C4<0>, C4<0>;
v0x2de87c0_0 .net/2u *"_ivl_0", 3 0, L_0x729223986060;  1 drivers
v0x2de88a0_0 .net "i", 3 0, v0x2dec150_0;  alias, 1 drivers
L_0x2dede60 .cmp/eq 4, v0x2dec150_0, L_0x729223986060;
S_0x2de8980 .scope module, "CI" "Cont_i" 3 94, 7 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /OUTPUT 4 "i_temp";
    .port_info 1 /INPUT 4 "i";
L_0x729223986018 .functor BUFT 1, C4<0001>, C4<0>, C4<0>, C4<0>;
v0x2de8bb0_0 .net/2u *"_ivl_0", 3 0, L_0x729223986018;  1 drivers
v0x2de8cb0_0 .net "i", 3 0, v0x2dec150_0;  alias, 1 drivers
v0x2de8dc0_0 .net "i_temp", 3 0, L_0x2dedcd0;  alias, 1 drivers
L_0x2dedcd0 .arith/sum 4, v0x2dec150_0, L_0x729223986018;
S_0x2de8ee0 .scope module, "CTRL" "Control_mult" 3 129, 8 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "init";
    .port_info 3 /INPUT 1 "CONTROL";
    .port_info 4 /INPUT 1 "DONE";
    .port_info 5 /OUTPUT 1 "load_A";
    .port_info 6 /OUTPUT 1 "load_C";
    .port_info 7 /OUTPUT 1 "load_D";
    .port_info 8 /OUTPUT 1 "load_i";
    .port_info 9 /OUTPUT 1 "DSHT";
    .port_info 10 /OUTPUT 1 "done";
P_0x2de9110 .param/l "S_ADDi_DS" 0 8 38, C4<0111>;
P_0x2de9150 .param/l "S_Ai0" 0 8 35, C4<0100>;
P_0x2de9190 .param/l "S_Ai1" 0 8 36, C4<0101>;
P_0x2de91d0 .param/l "S_CHK_i" 0 8 37, C4<0110>;
P_0x2de9210 .param/l "S_COMP_Ai" 0 8 34, C4<0011>;
P_0x2de9250 .param/l "S_DONE" 0 8 39, C4<1000>;
P_0x2de9290 .param/l "S_INIT" 0 8 31, C4<0000>;
P_0x2de92d0 .param/l "S_LOAD" 0 8 32, C4<0001>;
P_0x2de9310 .param/l "S_SLT_Ai" 0 8 33, C4<0010>;
v0x2de9970_0 .net "CONTROL", 0 0, L_0x2deddc0;  alias, 1 drivers
v0x2de9a80_0 .net "DONE", 0 0, L_0x2dede60;  alias, 1 drivers
v0x2de9b40_0 .var "DSHT", 0 0;
v0x2de9be0_0 .net "clk", 0 0, v0x2ded960_0;  alias, 1 drivers
v0x2de9c80_0 .var "done", 0 0;
v0x2de9d70_0 .net "init", 0 0, v0x2dedb40_0;  alias, 1 drivers
v0x2de9e30_0 .var "load_A", 0 0;
v0x2de9ef0_0 .var "load_C", 0 0;
v0x2de9fb0_0 .var "load_D", 0 0;
v0x2dea100_0 .var "load_i", 0 0;
v0x2dea1c0_0 .var "next_state", 3 0;
v0x2dea2a0_0 .net "rst", 0 0, v0x2dedc30_0;  alias, 1 drivers
v0x2dea360_0 .var "state", 3 0;
E_0x2dccd50 .event anyedge, v0x2dea360_0;
E_0x2dcd1e0 .event anyedge, v0x2dea360_0, v0x2de9d70_0, v0x2dabea0_0, v0x2de8700_0;
E_0x2de9910 .event posedge, v0x2dea2a0_0, v0x2de9be0_0;
S_0x2dea600 .scope module, "RA" "Reg_A" 3 42, 9 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "rst";
    .port_info 1 /INPUT 1 "clk";
    .port_info 2 /INPUT 1 "load_A";
    .port_info 3 /INPUT 16 "Ain";
    .port_info 4 /OUTPUT 16 "A";
v0x2dea8c0_0 .var "A", 15 0;
v0x2dea9d0_0 .net "Ain", 15 0, v0x2ded680_0;  alias, 1 drivers
v0x2deaa90_0 .net "clk", 0 0, v0x2ded960_0;  alias, 1 drivers
v0x2deab90_0 .net "load_A", 0 0, v0x2de9e30_0;  alias, 1 drivers
v0x2deac60_0 .net "rst", 0 0, v0x2dedc30_0;  alias, 1 drivers
E_0x2dea840 .event posedge, v0x2de9be0_0;
S_0x2deada0 .scope module, "RC" "Reg_C" 3 68, 10 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "rst";
    .port_info 1 /INPUT 1 "clk";
    .port_info 2 /INPUT 1 "load_C";
    .port_info 3 /INPUT 32 "C_temp";
    .port_info 4 /OUTPUT 32 "C";
v0x2deb030_0 .var "C", 31 0;
v0x2deb140_0 .net "C_temp", 31 0, L_0x2dfe130;  alias, 1 drivers
v0x2deb210_0 .net "clk", 0 0, v0x2ded960_0;  alias, 1 drivers
v0x2deb330_0 .net "load_C", 0 0, v0x2de9ef0_0;  alias, 1 drivers
v0x2deb3d0_0 .net "rst", 0 0, v0x2dedc30_0;  alias, 1 drivers
S_0x2deb550 .scope module, "RD" "Reg_D" 3 54, 11 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "rst";
    .port_info 1 /INPUT 1 "clk";
    .port_info 2 /INPUT 1 "load_D";
    .port_info 3 /INPUT 1 "DSHT";
    .port_info 4 /INPUT 16 "B";
    .port_info 5 /OUTPUT 16 "D";
v0x2deb770_0 .net "B", 15 0, v0x2ded7b0_0;  alias, 1 drivers
v0x2deb870_0 .var "D", 15 0;
v0x2deb930_0 .net "DSHT", 0 0, v0x2de9b40_0;  alias, 1 drivers
v0x2deba00_0 .net "clk", 0 0, v0x2ded960_0;  alias, 1 drivers
v0x2debaa0_0 .net "load_D", 0 0, v0x2de9fb0_0;  alias, 1 drivers
v0x2debb90_0 .net "rst", 0 0, v0x2dedc30_0;  alias, 1 drivers
S_0x2debcb0 .scope module, "RI" "Reg_i" 3 81, 12 1 0, S_0x2dc0f30;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "rst";
    .port_info 1 /INPUT 1 "clk";
    .port_info 2 /INPUT 1 "load_i";
    .port_info 3 /INPUT 4 "i_temp";
    .port_info 4 /OUTPUT 4 "i";
v0x2dec000_0 .net "clk", 0 0, v0x2ded960_0;  alias, 1 drivers
v0x2dec150_0 .var "i", 3 0;
v0x2dec210_0 .net "i_temp", 3 0, L_0x2dedcd0;  alias, 1 drivers
v0x2dec310_0 .net "load_i", 0 0, v0x2dea100_0;  alias, 1 drivers
v0x2dec3e0_0 .net "rst", 0 0, v0x2dedc30_0;  alias, 1 drivers
    .scope S_0x2dea600;
T_0 ;
    %wait E_0x2dea840;
    %load/vec4 v0x2deac60_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x2dea8c0_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0x2deab90_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %load/vec4 v0x2dea9d0_0;
    %assign/vec4 v0x2dea8c0_0, 0;
T_0.2 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
    .scope S_0x2deb550;
T_1 ;
    %wait E_0x2dea840;
    %load/vec4 v0x2debb90_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_1.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x2deb870_0, 0;
    %jmp T_1.1;
T_1.0 ;
    %load/vec4 v0x2debaa0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_1.2, 8;
    %load/vec4 v0x2deb770_0;
    %assign/vec4 v0x2deb870_0, 0;
    %jmp T_1.3;
T_1.2 ;
    %load/vec4 v0x2deb930_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_1.4, 8;
    %load/vec4 v0x2deb870_0;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %shiftl 4;
    %assign/vec4 v0x2deb870_0, 0;
T_1.4 ;
T_1.3 ;
T_1.1 ;
    %jmp T_1;
    .thread T_1;
    .scope S_0x2deada0;
T_2 ;
    %wait E_0x2dea840;
    %load/vec4 v0x2deb3d0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.0, 8;
    %pushi/vec4 0, 0, 32;
    %assign/vec4 v0x2deb030_0, 0;
    %jmp T_2.1;
T_2.0 ;
    %load/vec4 v0x2deb330_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.2, 8;
    %load/vec4 v0x2deb140_0;
    %assign/vec4 v0x2deb030_0, 0;
T_2.2 ;
T_2.1 ;
    %jmp T_2;
    .thread T_2;
    .scope S_0x2debcb0;
T_3 ;
    %wait E_0x2dea840;
    %load/vec4 v0x2dec3e0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.0, 8;
    %pushi/vec4 0, 0, 4;
    %assign/vec4 v0x2dec150_0, 0;
    %jmp T_3.1;
T_3.0 ;
    %load/vec4 v0x2dec310_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.2, 8;
    %load/vec4 v0x2dec210_0;
    %assign/vec4 v0x2dec150_0, 0;
T_3.2 ;
T_3.1 ;
    %jmp T_3;
    .thread T_3;
    .scope S_0x2de8ee0;
T_4 ;
    %wait E_0x2de9910;
    %load/vec4 v0x2dea2a0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_4.0, 8;
    %pushi/vec4 0, 0, 4;
    %assign/vec4 v0x2dea360_0, 0;
    %jmp T_4.1;
T_4.0 ;
    %load/vec4 v0x2dea1c0_0;
    %assign/vec4 v0x2dea360_0, 0;
T_4.1 ;
    %jmp T_4;
    .thread T_4;
    .scope S_0x2de8ee0;
T_5 ;
    %wait E_0x2dcd1e0;
    %load/vec4 v0x2dea360_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 4;
    %cmp/u;
    %jmp/1 T_5.0, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 4;
    %cmp/u;
    %jmp/1 T_5.1, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 4;
    %cmp/u;
    %jmp/1 T_5.2, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 4;
    %cmp/u;
    %jmp/1 T_5.3, 6;
    %dup/vec4;
    %pushi/vec4 4, 0, 4;
    %cmp/u;
    %jmp/1 T_5.4, 6;
    %dup/vec4;
    %pushi/vec4 5, 0, 4;
    %cmp/u;
    %jmp/1 T_5.5, 6;
    %dup/vec4;
    %pushi/vec4 6, 0, 4;
    %cmp/u;
    %jmp/1 T_5.6, 6;
    %dup/vec4;
    %pushi/vec4 7, 0, 4;
    %cmp/u;
    %jmp/1 T_5.7, 6;
    %dup/vec4;
    %pushi/vec4 8, 0, 4;
    %cmp/u;
    %jmp/1 T_5.8, 6;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.10;
T_5.0 ;
    %load/vec4 v0x2de9d70_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.11, 8;
    %pushi/vec4 1, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.12;
T_5.11 ;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
T_5.12 ;
    %jmp T_5.10;
T_5.1 ;
    %pushi/vec4 2, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.10;
T_5.2 ;
    %pushi/vec4 3, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.10;
T_5.3 ;
    %load/vec4 v0x2de9970_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.13, 8;
    %pushi/vec4 5, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.14;
T_5.13 ;
    %pushi/vec4 4, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
T_5.14 ;
    %jmp T_5.10;
T_5.4 ;
    %pushi/vec4 6, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.10;
T_5.5 ;
    %pushi/vec4 6, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.10;
T_5.6 ;
    %load/vec4 v0x2de9a80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.15, 8;
    %pushi/vec4 8, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.16;
T_5.15 ;
    %pushi/vec4 7, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
T_5.16 ;
    %jmp T_5.10;
T_5.7 ;
    %pushi/vec4 2, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.10;
T_5.8 ;
    %load/vec4 v0x2de9d70_0;
    %nor/r;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.17, 8;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
    %jmp T_5.18;
T_5.17 ;
    %pushi/vec4 8, 0, 4;
    %store/vec4 v0x2dea1c0_0, 0, 4;
T_5.18 ;
    %jmp T_5.10;
T_5.10 ;
    %pop/vec4 1;
    %jmp T_5;
    .thread T_5, $push;
    .scope S_0x2de8ee0;
T_6 ;
    %wait E_0x2dccd50;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2de9e30_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2de9ef0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2de9fb0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2dea100_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2de9b40_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2de9c80_0, 0, 1;
    %load/vec4 v0x2dea360_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 4;
    %cmp/u;
    %jmp/1 T_6.0, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 4;
    %cmp/u;
    %jmp/1 T_6.1, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 4;
    %cmp/u;
    %jmp/1 T_6.2, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 4;
    %cmp/u;
    %jmp/1 T_6.3, 6;
    %dup/vec4;
    %pushi/vec4 4, 0, 4;
    %cmp/u;
    %jmp/1 T_6.4, 6;
    %dup/vec4;
    %pushi/vec4 5, 0, 4;
    %cmp/u;
    %jmp/1 T_6.5, 6;
    %dup/vec4;
    %pushi/vec4 6, 0, 4;
    %cmp/u;
    %jmp/1 T_6.6, 6;
    %dup/vec4;
    %pushi/vec4 7, 0, 4;
    %cmp/u;
    %jmp/1 T_6.7, 6;
    %dup/vec4;
    %pushi/vec4 8, 0, 4;
    %cmp/u;
    %jmp/1 T_6.8, 6;
    %jmp T_6.10;
T_6.0 ;
    %jmp T_6.10;
T_6.1 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2de9e30_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2de9fb0_0, 0, 1;
    %jmp T_6.10;
T_6.2 ;
    %jmp T_6.10;
T_6.3 ;
    %jmp T_6.10;
T_6.4 ;
    %jmp T_6.10;
T_6.5 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2de9ef0_0, 0, 1;
    %jmp T_6.10;
T_6.6 ;
    %jmp T_6.10;
T_6.7 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2dea100_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2de9b40_0, 0, 1;
    %jmp T_6.10;
T_6.8 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2de9c80_0, 0, 1;
    %jmp T_6.10;
T_6.10 ;
    %pop/vec4 1;
    %jmp T_6;
    .thread T_6, $push;
    .scope S_0x2dc0c70;
T_7 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ded960_0, 0, 1;
T_7.0 ;
    %delay 10000, 0;
    %load/vec4 v0x2ded960_0;
    %inv;
    %store/vec4 v0x2ded960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x2ded960_0;
    %inv;
    %store/vec4 v0x2ded960_0, 0, 1;
    %jmp T_7.0;
T_7.1 ;
    %end;
    .thread T_7;
    .scope S_0x2dc0c70;
T_8 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2dedc30_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2dedb40_0, 0, 1;
    %pushi/vec4 5, 0, 16;
    %store/vec4 v0x2ded680_0, 0, 16;
    %pushi/vec4 3, 0, 16;
    %store/vec4 v0x2ded7b0_0, 0, 16;
    %delay 40000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2dedc30_0, 0, 1;
    %wait E_0x2dea840;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2dedb40_0, 0, 1;
    %wait E_0x2dea840;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2dedb40_0, 0, 1;
T_8.0 ;
    %load/vec4 v0x2deda00_0;
    %cmpi/ne 1, 0, 1;
    %jmp/0xz T_8.1, 6;
    %wait E_0x2dc2b10;
    %jmp T_8.0;
T_8.1 ;
    %vpi_call 2 116 "$display", "=================================" {0 0 0};
    %vpi_call 2 117 "$display", "A = %d", v0x2ded680_0 {0 0 0};
    %vpi_call 2 118 "$display", "B = %d", v0x2ded7b0_0 {0 0 0};
    %vpi_call 2 119 "$display", "Resultado = %d", v0x2ded8c0_0 {0 0 0};
    %vpi_call 2 120 "$display", "=================================" {0 0 0};
    %delay 50000, 0;
    %vpi_call 2 128 "$finish" {0 0 0};
    %end;
    .thread T_8;
    .scope S_0x2dc0c70;
T_9 ;
    %vpi_call 2 140 "$dumpfile", "Mul_Top_TB.vcd" {0 0 0};
    %vpi_call 2 141 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x2dc0c70 {0 0 0};
    %end;
    .thread T_9;
# The file index is used to find the file name in the following table.
:file_names 13;
    "N/A";
    "<interactive>";
    "Mul_Top_TB.v";
    "Mul_Top.v";
    "ADD_D.v";
    "Comp_Ai.v";
    "Check_i.v";
    "Cont_i.v";
    "Control_mult.v";
    "Reg_A.v";
    "Reg_C.v";
    "Reg_D.v";
    "Reg_i.v";
# EOF
